"""Add color website and description fields

Revision ID: 9f927a2e9c19
Revises: 531bc962092f
Create Date: 2026-01-10 19:09:01.857427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9f927a2e9c19'
down_revision: Union[str, Sequence[str], None] = '531bc962092f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscriptions', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscriptions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('subscriptions', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subscriptions', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('subscriptions', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscriptions', 'description')
    op.drop_column('subscriptions', 'website')
    op.drop_column('subscriptions', 'color')
    # ### end Alembic commands ###
